# Generated by Django 4.0.6 on 2023-05-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='owner',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='job_role',
            field=models.CharField(default='', max_length=255),
        ),
    ]
