# Generated by Django 4.0.6 on 2023-05-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_shortlisted'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('job_role', models.CharField(max_length=255)),
                ('total_ques_to_ask', models.IntegerField()),
                ('question_index', models.IntegerField()),
                ('question', models.CharField(max_length=255)),
                ('user_response', models.CharField(max_length=255)),
                ('ai_rating', models.IntegerField()),
            ],
        ),
    ]
